# === START: .github/workflows/purge-cloudflare.yml ===
name: Purge Cloudflare cache

on:
  push:
    branches: [ "main" ]

jobs:
  purge:
    # Only run if both secrets exist (avoids red X before you add them)
    if: ${{ secrets.CLOUDFLARE_API_TOKEN != '' && secrets.CLOUDFLARE_ZONE_ID != '' }}
    runs-on: ubuntu-latest
    steps:
      - name: Purge everything
        run: |
          curl -sS -X POST "https://api.cloudflare.com/client/v4/zones/${{ secrets.CLOUDFLARE_ZONE_ID }}/purge_cache" \
            -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_API_TOKEN }}" \
            -H "Content-Type: application/json" \
            --data '{"purge_everything":true}'
      - name: Done
        run: echo "Sent purge request to Cloudflare."

  skip:
    if: ${{ !(secrets.CLOUDFLARE_API_TOKEN != '' && secrets.CLOUDFLARE_ZONE_ID != '') }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Cloudflare secrets not set. Skipping purge."
          echo "Add CLOUDFLARE_API_TOKEN and CLOUDFLARE_ZONE_ID in repo settings."
# === END: .github/workflows/purge-cloudflare.yml ===
